/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ResolucaoLitigiosRouteImport } from './routes/resolucao-litigios'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PortefolioRouteImport } from './routes/portefolio'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminRecuperarRouteImport } from './routes/admin.recuperar'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminPortfolioRouteImport } from './routes/_admin/admin.portfolio'
import { Route as AdminAdminObrasRouteImport } from './routes/_admin/admin.obras'
import { Route as AdminAdminComoUsarRouteImport } from './routes/_admin/admin.como-usar'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolucaoLitigiosRoute = ResolucaoLitigiosRouteImport.update({
  id: '/resolucao-litigios',
  path: '/resolucao-litigios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PortefolioRoute = PortefolioRouteImport.update({
  id: '/portefolio',
  path: '/portefolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicosRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecuperarRoute = AdminRecuperarRouteImport.update({
  id: '/admin/recuperar',
  path: '/admin/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPortfolioRoute = AdminAdminPortfolioRouteImport.update({
  id: '/admin/portfolio',
  path: '/admin/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminObrasRoute = AdminAdminObrasRouteImport.update({
  id: '/admin/obras',
  path: '/admin/obras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminComoUsarRoute = AdminAdminComoUsarRouteImport.update({
  id: '/admin/como-usar',
  path: '/admin/como-usar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/obras': typeof ObrasRoute
  '/portefolio': typeof PortefolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/resolucao-litigios': typeof ResolucaoLitigiosRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recuperar': typeof AdminRecuperarRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/admin/como-usar': typeof AdminAdminComoUsarRoute
  '/admin/obras': typeof AdminAdminObrasRoute
  '/admin/portfolio': typeof AdminAdminPortfolioRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/obras': typeof ObrasRoute
  '/portefolio': typeof PortefolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/resolucao-litigios': typeof ResolucaoLitigiosRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recuperar': typeof AdminRecuperarRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/admin/como-usar': typeof AdminAdminComoUsarRoute
  '/admin/obras': typeof AdminAdminObrasRoute
  '/admin/portfolio': typeof AdminAdminPortfolioRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/obras': typeof ObrasRoute
  '/portefolio': typeof PortefolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/resolucao-litigios': typeof ResolucaoLitigiosRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recuperar': typeof AdminRecuperarRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/_admin/admin/como-usar': typeof AdminAdminComoUsarRoute
  '/_admin/admin/obras': typeof AdminAdminObrasRoute
  '/_admin/admin/portfolio': typeof AdminAdminPortfolioRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/obras'
    | '/portefolio'
    | '/privacidade'
    | '/resolucao-litigios'
    | '/servicos'
    | '/sobre'
    | '/admin/login'
    | '/admin/recuperar'
    | '/admin/reset-password'
    | '/areas/$slug'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/admin/como-usar'
    | '/admin/obras'
    | '/admin/portfolio'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/obras'
    | '/portefolio'
    | '/privacidade'
    | '/resolucao-litigios'
    | '/servicos'
    | '/sobre'
    | '/admin/login'
    | '/admin/recuperar'
    | '/admin/reset-password'
    | '/areas/$slug'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/admin/como-usar'
    | '/admin/obras'
    | '/admin/portfolio'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/contacto'
    | '/obras'
    | '/portefolio'
    | '/privacidade'
    | '/resolucao-litigios'
    | '/servicos'
    | '/sobre'
    | '/admin/login'
    | '/admin/recuperar'
    | '/admin/reset-password'
    | '/areas/$slug'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/_admin/admin/como-usar'
    | '/_admin/admin/obras'
    | '/_admin/admin/portfolio'
    | '/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  ObrasRoute: typeof ObrasRoute
  PortefolioRoute: typeof PortefolioRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResolucaoLitigiosRoute: typeof ResolucaoLitigiosRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  SobreRoute: typeof SobreRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRecuperarRoute: typeof AdminRecuperarRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AreasSlugRoute: typeof AreasSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolucao-litigios': {
      id: '/resolucao-litigios'
      path: '/resolucao-litigios'
      fullPath: '/resolucao-litigios'
      preLoaderRoute: typeof ResolucaoLitigiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portefolio': {
      id: '/portefolio'
      path: '/portefolio'
      fullPath: '/portefolio'
      preLoaderRoute: typeof PortefolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recuperar': {
      id: '/admin/recuperar'
      path: '/admin/recuperar'
      fullPath: '/admin/recuperar'
      preLoaderRoute: typeof AdminRecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/portfolio': {
      id: '/_admin/admin/portfolio'
      path: '/admin/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminAdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/obras': {
      id: '/_admin/admin/obras'
      path: '/admin/obras'
      fullPath: '/admin/obras'
      preLoaderRoute: typeof AdminAdminObrasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/como-usar': {
      id: '/_admin/admin/como-usar'
      path: '/admin/como-usar'
      fullPath: '/admin/como-usar'
      preLoaderRoute: typeof AdminAdminComoUsarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminComoUsarRoute: typeof AdminAdminComoUsarRoute
  AdminAdminObrasRoute: typeof AdminAdminObrasRoute
  AdminAdminPortfolioRoute: typeof AdminAdminPortfolioRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminComoUsarRoute: AdminAdminComoUsarRoute,
  AdminAdminObrasRoute: AdminAdminObrasRoute,
  AdminAdminPortfolioRoute: AdminAdminPortfolioRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServicosRouteChildren {
  ServicosSlugRoute: typeof ServicosSlugRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosSlugRoute: ServicosSlugRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactoRoute: ContactoRoute,
  ObrasRoute: ObrasRoute,
  PortefolioRoute: PortefolioRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResolucaoLitigiosRoute: ResolucaoLitigiosRoute,
  ServicosRoute: ServicosRouteWithChildren,
  SobreRoute: SobreRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRecuperarRoute: AdminRecuperarRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AreasSlugRoute: AreasSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
