/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ResolucaoLitigiosRouteImport } from './routes/resolucao-litigios'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PortefolioRouteImport } from './routes/portefolio'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolucaoLitigiosRoute = ResolucaoLitigiosRouteImport.update({
  id: '/resolucao-litigios',
  path: '/resolucao-litigios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PortefolioRoute = PortefolioRouteImport.update({
  id: '/portefolio',
  path: '/portefolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicosRoute,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/portefolio': typeof PortefolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/resolucao-litigios': typeof ResolucaoLitigiosRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/portefolio': typeof PortefolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/resolucao-litigios': typeof ResolucaoLitigiosRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/portefolio': typeof PortefolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/resolucao-litigios': typeof ResolucaoLitigiosRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/portefolio'
    | '/privacidade'
    | '/resolucao-litigios'
    | '/servicos'
    | '/sobre'
    | '/areas/$slug'
    | '/servicos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/portefolio'
    | '/privacidade'
    | '/resolucao-litigios'
    | '/servicos'
    | '/sobre'
    | '/areas/$slug'
    | '/servicos/$slug'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/portefolio'
    | '/privacidade'
    | '/resolucao-litigios'
    | '/servicos'
    | '/sobre'
    | '/areas/$slug'
    | '/servicos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  PortefolioRoute: typeof PortefolioRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResolucaoLitigiosRoute: typeof ResolucaoLitigiosRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  SobreRoute: typeof SobreRoute
  AreasSlugRoute: typeof AreasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolucao-litigios': {
      id: '/resolucao-litigios'
      path: '/resolucao-litigios'
      fullPath: '/resolucao-litigios'
      preLoaderRoute: typeof ResolucaoLitigiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portefolio': {
      id: '/portefolio'
      path: '/portefolio'
      fullPath: '/portefolio'
      preLoaderRoute: typeof PortefolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicosRouteChildren {
  ServicosSlugRoute: typeof ServicosSlugRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosSlugRoute: ServicosSlugRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  PortefolioRoute: PortefolioRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResolucaoLitigiosRoute: ResolucaoLitigiosRoute,
  ServicosRoute: ServicosRouteWithChildren,
  SobreRoute: SobreRoute,
  AreasSlugRoute: AreasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
